=== micaelfulle/trabalhoimplementacao/src/Xml/udescdb.xsd
<?xml version="1.0" encoding="UTF-8"?>
    <xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.udesc.br"
           xmlns="http://www.udesc.br"
           elementFormDefault="qualified">

	<xsd:element name="inserts">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="db" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="table" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="column" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="name" />
													<xsd:element name="value" />
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
									<xsd:attribute name="name" />
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="name" />
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:key name="DBId">
			<xsd:selector xpath="db" />
			<xsd:field xpath="@name" />
		</xsd:key>

	</xsd:element>

</xsd:schema>

=== micaelfulle/trabalhoimplementacao/src/Xml/Teste.xml
<?xml version="1.0" encoding="UTF-8"?>
<insert:table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.udesc.br udescdb.xsd"
          xmlns:insert="http://www.udesc.br">


    <inserts>
        <insert>
            <db>Banco</db>
            <table>xpto</table>
            <columns>
                <column>
                    <name>col1</name>
                    <value>1</value>
                </column>
                <column>
                    <name>col2</name>
                    <value>'abc'</value>
                </column>
                <column>
                    <name>col3</name>
                    <value>3.5</value>
                </column>
            </columns>
        </insert>

    </inserts>

</insert:table>
